[project]
name = "minimind"
version = "0.1.0"
description = "Minimal project scaffold."
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]